# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_auto_20170330_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='owner',
        ),
    ]
