# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0005_auto_20170330_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
