# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0007_auto_20170330_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='other_info',
            field=models.TextField(null=True),
        ),
    ]
